/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MACYielding.java
 *
 * Created on Aug 3, 2012, 12:28:29 PM
 */

package tamfinal;

import java.io.*;
import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author egc10
 */
public class MACYielding extends javax.swing.JFrame {
    public static String filepath,strkey,digestB641;
    /** Creates new form MACYielding */
    public MACYielding() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Select a file:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(55, 166, 77, 17);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(132, 163, 244, 20);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/browse.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(210, 235, 100, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MACode is:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(55, 330, 72, 17);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(132, 327, 244, 20);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/createmac.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(210, 380, 125, 30);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/macappend.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(330, 480, 125, 30);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/next.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(470, 480, 100, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/macyielding.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            JFileChooser fc=new JFileChooser();
            int a=fc.showOpenDialog(null);
            if(a==JFileChooser.APPROVE_OPTION)
            {
                File fileToOpen=fc.getSelectedFile();
                jTextField1.setText(filepath=fileToOpen.toString());
            }

        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            strkey = "NItY4ophQ==";
            SecretKeySpec key = new SecretKeySpec(strkey.getBytes("UTF-8"), "HmacMD5");
            String s,s1;
            Mac mac = Mac.getInstance(key.getAlgorithm());
            mac.init(key);
            FileInputStream fis = new FileInputStream(filepath);
            FileOutputStream fos=new FileOutputStream("d:\\data1.txt");
            PrintStream ps=new PrintStream(fos);
            DataInputStream dis = new DataInputStream(fis);
            BufferedReader br = new BufferedReader(new InputStreamReader(dis));
            while ((s = dis.readLine()) != null){
                ps.print(s);
            }
            FileInputStream fis1 = new FileInputStream("d:\\data1.txt");
            DataInputStream dis1 = new DataInputStream(fis1);
            BufferedReader br1 = new BufferedReader(new InputStreamReader(dis1));
            s1 = dis1.readLine();
            byte[] utf8 = s1.getBytes("UTF8");
            byte[] digest = mac.doFinal(utf8);
            digestB641 = new sun.misc.BASE64Encoder().encode(digest);
            jTextField2.setText(digestB641);
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            FileWriter fstream = new FileWriter(filepath,true);
            BufferedWriter out = new BufferedWriter(fstream);
            out.newLine();
            out.write(strkey);
            out.newLine();
            out.write(digestB641);
            out.close();
            JOptionPane.showMessageDialog(null,"MAC is appended");
            
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
            Fileciphering fc=new Fileciphering();
            fc.setVisible(true);
            this.dispose();
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {public void run() {new MACYielding().setVisible(true);}});
        try{

        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}
